server:
  port: 9090

spring:
  application:
    name: origin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/origin?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

